spring:
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://52.230.104.188:3306/Pharmacy?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1590
  jpa:
    hibernate:
      ddl-auto: create
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh